FROM node:18.18.0

WORKDIR /usr/src/app

RUN mkdir video-storage

RUN npm install -g @nestjs/cli

# Copy application dependency manifests to the container image.
# Copying this first prevents re-running npm install on every code change.
COPY package*.json ./

COPY . .

CMD yarn install && \
  nest start --watch
